### ISSUE TITLE
MadVR and Cinema Mode

### ISSUE THREAD

**Issue by xzener** [MediaBrowser/Emby.Theater.Windows#316]
Tested with Cinema Mode enabled, with MadVR, and change monitor refresh enabled (not sure if this is needed, it changes to 24hz if that option isn't enabled)...  Cinema Mode trailers are switching the refresh rate to 24hz (trailers don't look good), movie starts and looks great. Stopping the video brings the details screen back but its stuck in 24hz. Looks like we need a little bit more tweaking.

Tried another, after first trailer the player froze (dark screen). Here is the log...

https://onedrive.liv...ithint=file,txt

**Comment by njoak** [comment]
In case it is related and of help, I too have trouble getting the refresh rate to change back sometimes and made some tests with trailers and live TV (serverWMC). 

I could not once get the refresh rate to change back after playing:

* a trailer from a movie details page
* a trailer from the trailer channel
* live TV.

Trouble with this as I see it, is that 
- navigation in ET is stutters if the refresh rate is ~24 or 25 (below 50?) 
- and once the refresh rate does not switch back after playing one of the above, it gets "stuck" - it doesn't switch back to original setting after playing something that usually does switch back.

Occasionally the switch back doesn't work for me when playing movies or tv episodes as well. FYI I have refresh rate change activated both in the ET settings gui, and in madVR. Had trouble getting it to work at all otherwise.

For reference I mentioned this in a post on the emby forum as well:
http://emby.media/community/index.php?/topic/29774-new-version-testing/?view=findpost&p=291202
